name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Change wrapper permissions
      run: chmod +x ./hello.c
    - name: hello
      run: gcc -Wall hello.c -o hello
    - name: execute
      run: ./hello
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
